

test('Prueba paso el test correctamente', () => {
    
        if (1 > 1) 
        {
            throw new Error('Erro en la prueba');
        }
    
     })